export const SET_EMAIL_SETTINGS_REQUEST = "SET_EMAIL_SETTINGS_REQUEST"
export const SET_EMAIL_SETTINGS_SUCCESS = "SET_EMAIL_SETTINGS_SUCCESS"
export const SET_EMAIL_SETTINGS_FAILURE = "SET_EMAIL_SETTINGS_FAILURE"
