export const ADD_EMAIL_CONTACTS_REQUEST = "ADD_EMAIL_CONTACTS_REQUEST"
export const ADD_EMAIL_CONTACTS_SUCCESS = "ADD_EMAIL_CONTACTS_SUCCESS"
export const ADD_EMAIL_CONTACTS_FAILURE = "ADD_EMAIL_CONTACTS_FAILURE"
