export const FETCH_ENRICH_CSV_REQUEST = "FETCH_ENRICH_CSV_REQUEST"
export const FETCH_ENRICH_CSV_SUCCESS = "FETCH_ENRICH_CSV_SUCCESS"
export const FETCH_ENRICH_CSV_FAILURE = "FETCH_ENRICH_CSV_FAILURE"
