export const FETCH_SAVED_USERS_REQUEST = "FETCH_SAVED_USERS_REQUEST"
export const FETCH_SAVED_USERS_SUCCESS = "FETCH_SAVED_USERS_SUCCESS"
export const FETCH_SAVED_USERS_FAILURE = "FETCH_SAVED_USERS_FAILURE";
