export const FETCH_EMAIL_CONTACTS_REQUEST = "FETCH_EMAIL_CONTACTS_REQUEST"
export const FETCH_EMAIL_CONTACTS_SUCCESS = "FETCH_EMAIL_CONTACTS_SUCCESS"
export const FETCH_EMAIL_CONTACTS_FAILURE = "FETCH_EMAIL_CONTACTS_FAILURE"
