export const FETCH_EMAIL_SETTINGS_REQUEST = "FETCH_EMAIL_SETTINGS_REQUEST"
export const FETCH_EMAIL_SETTINGS_SUCCESS = "FETCH_EMAIL_SETTINGS_SUCCESS"
export const FETCH_EMAIL_SETTINGS_FAILURE = "FETCH_EMAIL_SETTINGS_FAILURE"
